# Masking NumPy arrays
Masking is a term used for selecting entries in arrays via conditional / logical queries on the data. To do this, we need to use [numpy arrays](https://numpy.org/doc/stable/user/basics.creation.html).

NumPy is a package for scientific computing and efficient numerical operations in Python.

NumPy arrays (multidimensional, homogeneous arrays of fixed-size items) are the basic data structure.

Per definition, they contain [numerical data types](https://numpy.org/doc/stable/user/basics.types.html) only.

To use NumPy, we need to [import](https://docs.python.org/3/reference/simple_stmts.html#import) it first, then we can define a NumPy array:

In [1]:
import numpy
measurements = numpy.asarray([1, 17, 25, 3, 5, 25, 12])
measurements

array([ 1, 17, 25,  3,  5, 25, 12])

In [2]:
type(measurements)

numpy.ndarray

In [3]:
measurements.dtype

dtype('int64')

Next, we create the mask, e.g., the condition for all measurements that are above a given threshold:

In [4]:
mask = measurements > 10
mask

array([False,  True,  True, False, False,  True,  True])

We can now apply that mask via `[]`operator to our data to retrieve a new array that only contains masked values.

In [5]:
measurements[mask]

array([17, 25, 25, 12])

All this can also be done in one line. In addition, more complex conditions can be defined with logical operators like `&` (and) or `|` (or), where combined conditions must be separated by parentheses `()`. 

In [6]:
measurements[(measurements > 10) & (measurements < 20)]

array([17, 12])

## Exercises
Use masking to select all measurements equal 25



Use masking to select all measurements equal and below 5 or above 20